### ISSUE TITLE
Lower Node Engines to >=6?

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/lighthouse-security#14]
Like [GoogleChrome/lighthouse engines setting](https://github.com/GoogleChrome/lighthouse/blob/master/package.json#L11)

**Comment by markomalis** [comment]
we are using async await so the lowest is 7.6.0

**Comment by jbmoelker** [comment]
How about we lower it to 7.6.0 and add a note under [Run from CLI](https://github.com/voorhoede/lighthouse-security#run-from-cli) like [GoogleChrome/lighthouse](https://github.com/GoogleChrome/lighthouse#using-the-node-cli) with:

*Lighthouse-security requires [Node.js](https://nodejs.org) 7.6.0 or later.*

```sh
lighthouse-security <url> [options]
```

*If you're using Node < 7.6 you can use [babel-node](https://babeljs.io/docs/usage/cli/#babel-node)*:

```sh
babel-node lighthouse-security <url> [options]
```
